services:
  server:
    container_name: apache
    build:
      context: .
      target: development
    ports:
      - 9000:80
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - db-password
    environment:
      - DB_HOST=db
      - DB_NAME=example
      - DB_USER=root
      - PASSWORD_FILE_PATH=/run/secrets/db-password
  
  db:
    container_name: mariadb
    image: mariadb
    restart: always
    user: root
    secrets:
      - db-password
    volumes:
      - ./mariadb-data:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=example
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 3306:3306
    healthcheck:
      test:
        [
          "CMD",
          "/usr/local/bin/healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - PMA_ARBITRARY=1

secrets:
  db-password:
    file: db/password.txt